### ISSUE TITLE
Setting unique wallpaper per device

### ISSUE THREAD

**Issue by ropelletier** [jamf/JAWA#45]
Apologies if this should not belong here, but I am hoping to get some assistance. I have been trying to configure custom wallpaper for each of our iOS devices. Unfortunately, I am unable to even get my test to work. I did post something in the community and opened up a ticket with JAMF, but have not had any answers so far. Here is the community post: https://community.jamf.com/t5/jamf-pro/jamf-pro-api-wallpaper-base64-encoded-giving-an-error-problem/td-p/301599

My goal was to rewrite this in python (My skillset is PHP, not python, which is why my proof of concept is in PHP, but I can manage). That being said, it would be amazing if PHP were also an option in JAWA.

I have watched the section of the YouTube demonstration here: https://www.youtube.com/watch?v=GicgP0tgwyM&ab_channel=Jamf
Specifically the section dealing with Unique wallpaper, but it would be very helpful if you could share the auto_wallpaper.py script. That would be very appreciated and a great first step to trying to figure out why this does not work. Thank you for your time and insight.

**Comment by ball42** [comment]
Hi there! 

Currently, I'm awaiting the necessary approvals to share that code publicly. This is to ensure compliance with our internal guidelines.  

In the meantime, while I'm not strong in PHP myself, I can say that the script you posted on Jamf Nation does look very similar to the method I used in the `auto_wallpaper.py` script.  Once difference I noted is that I used the `{jamf_pro_url}/JSSResource/mobiledevicecommands/command/Wallpaper` endpoint - this difference shouldn't matter as long as the XML is valid (and contains a big, nasty b64 blob), but it's worth trying.  

I'm closing this issue since it's re: JAWA workflows and not the application itself. For workflow-related queries and enhancements, could you please open a new issue in a JAWA workflows repository? This helps keep the projects organized.

Here's the link to the repository:  https://github.com/ball42/JAWA-Workflows

Thank you for your contributions to JAWA; may the workflows be with you.

Best regards,
Chris
